### ISSUE TITLE
Update HA GW template to use WS2016 image

### ISSUE THREAD

**Issue by mmarch** [mmarch/rds-templates#1]

**Comment by mmarch** [comment]
Also change itemDisplayName in metadata.json to say it's HA for Gateway and RDWeb, not full "High availability deployment"  to avoid confusion.

**Comment by mmarch** [comment]
created [PR#2863](https://github.com/Azure/azure-quickstart-templates/pull/2863)

**Comment by mmarch** [comment]
[PR#2923](https://github.com/Azure/azure-quickstart-templates/pull/2923) to change template title in metadata.json

**Comment by mmarch** [comment]
pull request still open and pending approval (for longer than a month!).... still waiting

**Comment by mmarch** [comment]
[PR#2923](https://github.com/Azure/azure-quickstart-templates/pull/2923) merged yesterday 2/28/2017. Closing.

**Comment by jasonagilbertson** [comment]
This issue was moved to Azure/RDS-Templates#8
