### ISSUE TITLE
Case sensitive parameters in azuredeploy.parameters.json in RDS HA-Gateway template 

### ISSUE THREAD

**Issue by fberson** [mmarch/rds-templates#14]
It seems like ARM is Case Sensitive and does not like the fact that the parameter.json file contains
```
       "BrokerServer": {
        "value": "broker.rdsgurus.com"
},
```
And the deployment.json contains
```
       "brokerServer": {
         "type": "string",
        "metadata": {
         "description": "FQDN for Broker Server"
         }
},
```
I would suggest to change the parameter in deployment.json to match the one in parameter.json

**Comment by mmarch** [comment]
best practices require parameters follow Camel case notation, so we should be using names starting with lowercase 
(azuredeploy.parameters.json parameters should match azuredeploy.json, and not vice versa)

**Comment by mmarch** [comment]
[PR #3304](https://github.com/Azure/azure-quickstart-templates/pull/3034)

**Comment by mmarch** [comment]
[PR #3304](https://github.com/Azure/azure-quickstart-templates/pull/3034) merged to Azure:master on 3/07/2017.  Closing...
