### ISSUE TITLE
Specify Subnet & Vnet in RDS HA-Gateway template

### ISSUE THREAD

**Issue by fberson** [mmarch/rds-templates#15]
The RD Session Collection High availability template does not allow you to specify the subnet as a parameter, where the RDS farm deployment template does allow this. This causes the template to fail if you choose a different name for the Vnet during the RDS farm deployment template.
I would suggest to change variable:
`"subnetName": "Subnet"`
Into the parameter adSubnetName, similar to how the current RDS farm deployment template also does this.

Same is true for the Vnet, the name is hardcoded as “vnet”. I would suggest to add a parameter adVnetName similar to how the current RDS farm deployment template does this

**Comment by mmarch** [comment]
fixed with [df30a4b](https://github.com/Azure/azure-quickstart-templates/commit/df30a4b7340f90b9efce5e983f7829cc38f7fec7)
"Added existingVnet and existingSubnet as parameter" (fberson) on Dec 12, 2016

PR: master [#2873](https://github.com/Azure/azure-quickstart-templates/pull/2873)
