### ISSUE TITLE
Unused variable rdshVmSize in RDS HA-Gateway template 

### ISSUE THREAD

**Issue by fberson** [mmarch/rds-templates#16]
The RD Session Collection High availability template has a variable rdshVmSize which is not used in the template
```
    "rdshVmSize": {
      "type": "string",
      "defaultValue": "Standard_D2",
      "metadata": {
        "description": "The size of the RDSH VMs"
      }
```

**Comment by mmarch** [comment]
should rename 'rdshVmSize' to 'vmSize', update description, pass the parameter to gw-vm-loop vm creation resource, and don't forget to rename the param in azuredeploy.parameters.json

**Comment by mmarch** [comment]
[PR #3031](https://github.com/Azure/azure-quickstart-templates/pull/3031) merged to azure today
