### ISSUE TITLE
RDS HA-Gateway template does not allow to specify imageSKU 

### ISSUE THREAD

**Issue by fberson** [mmarch/rds-templates#17]
The RD Session Collection High availability template has parameter imageSKU defined as below that allows to specify the SKU of the RDGW Server
```
    "imageSKU": {
      "type": "string",
      "allowedValues": [
        "2012-R2-Datacenter",
        "Windows-Server-Technical-Preview"
      ],
      "metadata": {
        "description": "Windows server SKU"
      },
      "defaultValue": "2012-R2-Datacenter"
},
```
However, the VM Resource in the template uses a variable imageSKU, which is set to 2012-R2-Datacenter
```
        "storageProfile": {
          "imageReference": {
            "publisher": "[variables('imagePublisher')]",
            "offer": "[variables('imageOffer')]",
            "sku": "[variables('imageSKU')]",
            "version": "latest"
          },
```
             The RDS farm deployment template does not allow to specify the imageSKU of the RD Gateway either. I would suggest to start using a parameter in both templates or remove the parameter here.

**Comment by mmarch** [comment]
fixed with [fadc439](https://github.com/Azure/azure-quickstart-templates/commit/fadc439ea324d546111da86b94963f894119d211)  "Update HA GW template for WS2016 RTM" (mmarch) on Dec 9, 2016
