### ISSUE TITLE
Typo in RD Session Collection High availability template

### ISSUE THREAD

**Issue by fberson** [mmarch/rds-templates#18]
There is a typo in the numberOfWebGwInstances parameter, it says 'Number of RDSH instances'
```
    "numberOfWebGwInstances": {
      "type": "int",
      "defaultValue": 2,
      "metadata": {
        "description": "Number of RDSH instances"
      }
},
```
Which also shows here: https://azure.microsoft.com/en-us/resources/templates/rds-deployment-ha-gateway/

**Comment by mmarch** [comment]
[PR #3032](https://github.com/Azure/azure-quickstart-templates/issues/3032) merged to Azure:master on 3/07/2017.  Closing.
