### ISSUE TITLE
Remove "rds with existing AD and custom image" template from Azure docs and github

### ISSUE THREAD

**Issue by cnicholson** [mmarch/rds-templates#21]
no need for this any longer since an admin can now run the "RDS farm with existing AD" template and then run the "update collection" template to get custom image.

One less template to keep up-to-date.
https://azure.microsoft.com/en-us/resources/templates/rds-deployment-custom-image-rdsh/

**Comment by mmarch** [comment]
[PR #3059](https://github.com/Azure/azure-quickstart-templates/pull/3059) created

**Comment by mmarch** [comment]
[PR #3059](https://github.com/Azure/azure-quickstart-templates/pull/3059) merged to Azure:master on 3/07/2017
