### ISSUE TITLE
Logon method RD Gateway causes Single Sign On to break

### ISSUE THREAD

**Issue by fberson** [mmarch/rds-templates#30]
The Quick Start Template "RDS farm deployment using existing active directory" configures the RD Gateway with the **LogonMethod** set to **AllowUserToSelectDuringConnection**. This causes RD Web Single Sign On to break.

Suggestion is to update the DSC Extension that is used to configure RD Gateway and set the **LogonMethod** to **Password**

**Comment by mmarch** [comment]
PR#3108 merged to Azure:master today. Closing.
