### ISSUE TITLE
Should allow WS2016 image in AD creation template

### ISSUE THREAD

**Issue by mmarch** [mmarch/rds-templates#8]
Currently we create WS2012R2 domain controller with rds-deployment.

https://github.com/Azure/azure-quickstart-templates/blob/master/active-directory-new-domain/azuredeploy.json has storageProfile/imageReference/sku hardcoded to '2012-R2-Datacenter'

**Comment by mmarch** [comment]
Issue #2800 in Azure/Azure-QuickStart-Templates:
[active-directory-new-domain template should allow create WS2016 DC](https://github.com/Azure/azure-quickstart-templates/issues/2800)

**Comment by mmarch** [comment]
PR #[2804](https://github.com/Azure/azure-quickstart-templates/pull/2804)

**Comment by mmarch** [comment]
this is fixed in AD creation template.  closing...

**Comment by jasonagilbertson** [comment]
This issue was moved to Azure/RDS-Templates#29
